name: Markdown Check

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  markdown_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install proselint
      run: |
        sudo add-apt-repository universe
        sudo apt-get update
        sudo apt-get install -y python3-proselint

    - name: Install write-good
      run: npm install -g write-good

    - name: Run Markdown Check
      run: |
        for file in $(find . -name "*.md"); do
          proselint "$file" || true
          write-good "$file" || true
        done
