name: Markdown Check

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  markdown_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install proselint
      run: |
        sudo add-apt-repository universe
        sudo apt-get update
        sudo apt-get install -y python3-proselint

    - name: Install write-good
      run: npm install -g write-good

    - name: Run Markdown Check
      run: |
        for file in $(find . -name "*.md"); do
          # Run proselint and write-good and capture the output
          proselint_output=$(proselint "$file" || true)
          write_good_output=$(write-good "$file" || true)

          # Check if there are any issues and set outputs
          if [ -n "$proselint_output" ]; then
            echo "::warning file=$file,line=1::Proselint issues found: $proselint_output"
          fi

          if [ -n "$write_good_output" ]; then
            echo "::warning file=$file,line=1::Write-good issues found: $write_good_output"
          fi
        done
