name: ShellCheck

on:
  push:
    paths:
      - '**/*.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install ShellCheck
      run: sudo apt-get install shellcheck

    - name: Run ShellCheck
      run: shellcheck **/*.sh

